# Generated by Django 4.2.1 on 2023-05-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='images/n/'),
        ),
    ]
