# Generated by Django 4.2.1 on 2023-05-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0003_news_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/p/')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
