# Generated by Django 4.2.1 on 2023-05-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data_delay',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
