# Generated by Django 4.2.1 on 2023-05-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0005_project_data_delay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/partners/')),
            ],
        ),
    ]
