# Generated by Django 4.2.1 on 2023-05-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0006_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=18)),
                ('subject', models.CharField(max_length=155)),
                ('message', models.CharField(max_length=2000)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
    ]
