# Generated by Django 4.2.1 on 2023-05-15 20:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0007_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilmiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('labs', 'Laboratoriyalar'), ('projects', 'Loyihalar'), ('ilmiy-uslubiy-ishlar', 'Ilmiy uslubiy ishlar')], max_length=50, unique=True)),
                ('page', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuzilma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('director', 'director'), ('ilmiy-kengash', 'Ilmiy kengash'), ('institut-kengashi', 'Institut kengashi')], max_length=50, unique=True)),
                ('page', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
