# Generated by Django 4.2.1 on 2023-05-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0009_alter_ilmiy_options_alter_tuzilma_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilmiy',
            name='type',
        ),
        migrations.AddField(
            model_name='ilmiy',
            name='slug',
            field=models.CharField(choices=[('labs', 'Laboratoriyalar'), ('projects', 'Loyihalar'), ('ilmiy-uslubiy-ishlar', 'Ilmiy uslubiy ishlar')], default='labs', max_length=50),
        ),
        migrations.AddField(
            model_name='ilmiy',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
